name: Coverity with Self-Hosted Runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, coverity]

    env:
      COVERITY_URL: ${{ secrets.COVERITY_URL }}
      COV_USER: ${{ secrets.COVERITY_USER }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      COVERITY_LICENSE: ${{ secrets.COVERITY_LICENSE }}
      SECURITY_GATE_ARGS: --new
      COVERITY_CHECKERS: --webapp-security
      SYNOPSYS_GITHUB_TOOLS_REPO: https://github.com/synopsys-sig-community/synopsys-github-tools
      COVERITY_STREAM_NAME: ${GITHUB_REPOSITORY}-${GITHUB_REF}


    steps:
      - uses: actions/checkout@v2

      - name: Get Synopsys GitHub Tools
        run: |
          git clone -q --depth 1 $SYNOPSYS_GITHUB_TOOLS_REPO
          pip3 install --upgrade pandas requests==2.26.0 urllib3==1.26.7 jsonapi-requests==0.6.2 tenacity==6.2.0 pygithub

      - name: Coverity License
        run: |
          echo $COVERITY_LICENSE > coverity-license.dat

      - name: Create Coverity Stream
        if: ${{github.event_name == 'push'}}
        # TODO: Should this only run for master, other specific names?
        run: |
          env
          echo Ensure that stream "$COVERITY_STREAM_NAME" exists
          cov-manage-im --url $COVERITY_URL --on-new-cert trust --mode streams --add -set name:"$COVERITY_STREAM_NAME" || true

      - name: Coverity Scan (Full analysis)
        if: ${{github.event_name == 'push'}}

        run: |
          cov-capture --dir idir --project-dir .
          cov-analyze --dir idir $COVERITY_CHECKERS
          cov-commit-defects --dir idir --on-new-cert trust --ticker-mode none --url $COVERITY_URL --on-new-cert trust --stream $COVERITY_STREAM --scm git --description "GitHub Workflow $GITHUB_WORKFLOW for $GITHUB_REPO" --version $GITHUB_SHA

      #- name: Export Coverity Results to SARIF (Full)
      #  run: python3 ./synopsys-github-tools/github-export-polaris-issues.py
      #  if: ${{github.event_name == 'push'}}

      #- name: Export Coverity Results to SARIF (Incremental)
      #  run: python3 ./synopsys-github-tools/github-export-coverity-issues.py --coverity-json ./.synopsys/polaris/data/coverity/*/idir/incremental-results/incremental-results.json --polaris --comment-on-github-pr
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  if: ${{github.event_name == 'pull_request'}}
      #  continue-on-error: true

      #- name: Upload SARIF file
      #  uses: github/codeql-action/upload-sarif@v1
      #  with:
      #    # Path to SARIF file relative to the root of the repository
      #    sarif_file: synopsys-coverity-github-sarif.json
